package test.org.cerberus.scenario;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import org.ow2.asmdex.ApplicationReader;
import org.ow2.asmdex.ApplicationVisitor;
import org.ow2.asmdex.ApplicationWriter;
import org.ow2.asmdex.Opcodes;


public class ASMTest {

	public static void main(String[] args) throws IOException {
		
		int api = Opcodes.ASM4;
		
		File inFile = new File("classes.dex");
		ApplicationReader ar = new ApplicationReader(api,inFile);
		ApplicationWriter aw = new ApplicationWriter(); 
		ApplicationVisitor aa = new ApplicationAdapterAnnotateCalls(api, aw);
		
		ar.accept(aa, 0);
		
		byte[] b = aw.toByteArray();
		FileOutputStream os = new FileOutputStream(new File("classes.dex"));
		os.write(b);
		
		os.flush();
		os.close();
	}
	
}
/*

---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatJellyBean;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatJellybeanMr2;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompatKitKat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatJellyBean$1;
signature : null
superName : Landroid/view/accessibility/AccessibilityNodeProvider;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatJellyBean$AccessibilityNodeInfoBridge;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatJellyBean;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatKitKat$1;
signature : null
superName : Landroid/view/accessibility/AccessibilityNodeProvider;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatKitKat$AccessibilityNodeInfoBridge;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatKitKat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompatIcsMr1;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompatJellyBean;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 4096
name : Landroid/support/v4/widget/AutoScrollHelper$1;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/AutoScrollHelper$ClampedScroller;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/AutoScrollHelper$ScrollAnimationRunnable;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/AutoScrollHelper;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/view/View$OnTouchListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ContentLoadingProgressBar$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ContentLoadingProgressBar$2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/ContentLoadingProgressBar;
signature : null
superName : Landroid/widget/ProgressBar;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 4096
name : Landroid/support/v4/widget/CursorAdapter$1;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/CursorAdapter$ChangeObserver;
signature : null
superName : Landroid/database/ContentObserver;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/CursorAdapter$MyDataSetObserver;
signature : null
superName : Landroid/database/DataSetObserver;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/CursorFilter$CursorFilterClient;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/CursorFilter;
signature : null
superName : Landroid/widget/Filter;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1537
name : Landroid/support/v4/widget/DrawerLayout$DrawerListener;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/DrawerLayout$LayoutParams;
signature : null
superName : Landroid/view/ViewGroup$MarginLayoutParams;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/widget/DrawerLayout$SavedState$1;
signature : [Ljava/lang/Object;, Landroid/os/Parcelable$Creator, <, Landroid/support/v4/widget/DrawerLayout$SavedState;, >;]
superName : Ljava/lang/Object;
interfaces : [Landroid/os/Parcelable$Creator;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/DrawerLayout$SavedState;
signature : null
superName : Landroid/view/View$BaseSavedState;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/DrawerLayout$ViewDragCallback$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/DrawerLayout;
signature : null
superName : Landroid/view/ViewGroup;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/EdgeEffectCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/EdgeEffectCompatIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 4096
name : Landroid/support/v4/widget/ExploreByTouchHelper$1;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/ListPopupWindowCompat$ListPopupWindowImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/ListPopupWindowCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ListPopupWindowCompatKitKat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/PopupMenuCompat$PopupMenuImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/PopupMenuCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/PopupMenuCompatKitKat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/ScrollerCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ScrollerCompatGingerbread;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ScrollerCompatIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/SearchViewCompat$OnCloseListenerCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/SearchViewCompat$OnQueryTextListenerCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SearchViewCompat;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/widget/SearchViewCompatHoneycomb$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/widget/SearchView$OnQueryTextListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/widget/SearchViewCompatHoneycomb$2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/widget/SearchView$OnCloseListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompatHoneycomb;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SearchViewCompatIcs$MySearchView;
signature : null
superName : Landroid/widget/SearchView;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompatIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1537
name : Landroid/support/v4/widget/SimpleCursorAdapter$CursorToStringConverter;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1537
name : Landroid/support/v4/widget/SimpleCursorAdapter$ViewBinder;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 4096
name : Landroid/support/v4/widget/SlidingPaneLayout$1;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$DisableLayerRunnable;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SlidingPaneLayout$LayoutParams;
signature : null
superName : Landroid/view/ViewGroup$MarginLayoutParams;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1537
name : Landroid/support/v4/widget/SlidingPaneLayout$PanelSlideListener;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/widget/SlidingPaneLayout$SavedState$1;
signature : [Ljava/lang/Object;, Landroid/os/Parcelable$Creator, <, Landroid/support/v4/widget/SlidingPaneLayout$SavedState;, >;]
superName : Ljava/lang/Object;
interfaces : [Landroid/os/Parcelable$Creator;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$SavedState;
signature : null
superName : Landroid/view/View$BaseSavedState;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1536
name : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SlidingPaneLayout;
signature : null
superName : Landroid/view/ViewGroup;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/widget/ViewDragHelper$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/view/animation/Interpolator;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ViewDragHelper$2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/ViewDragHelper$Callback;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/ViewDragHelper;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/BuildConfig;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Lcom/example/testandroid/MainActivity;
signature : null
superName : Landroid/app/Activity;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$attr;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$dimen;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$drawable;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$id;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$layout;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$menu;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$string;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R$style;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 17
name : Lcom/example/testandroid/R;
signature : null
superName : Ljava/lang/Object;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplHC;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/ActionBarDrawerToggle;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/DrawerLayout$DrawerListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/ActivityCompat;
signature : null
superName : Landroid/support/v4/content/ContextCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ActivityOptionsCompat$ActivityOptionsImplJB;
signature : null
superName : Landroid/support/v4/app/ActivityOptionsCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/app/BackStackRecord;
signature : null
superName : Landroid/support/v4/app/FragmentTransaction;
interfaces : [Landroid/support/v4/app/FragmentManager$BackStackEntry;, Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/DialogFragment;
signature : null
superName : Landroid/support/v4/app/Fragment;
interfaces : [Landroid/content/DialogInterface$OnCancelListener;, Landroid/content/DialogInterface$OnDismissListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/Fragment$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/FragmentContainer;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/FragmentActivity$2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/FragmentContainer;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/app/FragmentManagerImpl;
signature : null
superName : Landroid/support/v4/app/FragmentManager;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/app/FragmentPagerAdapter;
signature : null
superName : Landroid/support/v4/view/PagerAdapter;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/app/FragmentStatePagerAdapter;
signature : null
superName : Landroid/support/v4/view/PagerAdapter;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/ListFragment;
signature : null
superName : Landroid/support/v4/app/Fragment;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/app/LoaderManagerImpl$LoaderInfo;
signature : [Ljava/lang/Object;, Landroid/support/v4/content/Loader$OnLoadCompleteListener, <, Ljava/lang/Object;, >;]
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/content/Loader$OnLoadCompleteListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/LoaderManagerImpl;
signature : null
superName : Landroid/support/v4/app/LoaderManager;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NavUtils$NavUtilsImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/NavUtils$NavUtilsImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/NotificationCompat$BigPictureStyle;
signature : null
superName : Landroid/support/v4/app/NotificationCompat$Style;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/NotificationCompat$BigTextStyle;
signature : null
superName : Landroid/support/v4/app/NotificationCompat$Style;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/app/NotificationCompat$InboxStyle;
signature : null
superName : Landroid/support/v4/app/NotificationCompat$Style;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NotificationCompat$NotificationCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/NotificationCompat$NotificationCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NotificationCompat$NotificationCompatImplHoneycomb;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/NotificationCompat$NotificationCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NotificationCompat$NotificationCompatImplIceCreamSandwich;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/NotificationCompat$NotificationCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NotificationCompat$NotificationCompatImplJellybean;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/NotificationCompat$NotificationCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ShareCompat$ShareCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/ShareCompat$ShareCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImplHoneycomb;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImplJellybean;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/app/TaskStackBuilder$TaskStackBuilderImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/content/AsyncTaskLoader$LoadTask;
signature : [Landroid/support/v4/content/ModernAsyncTask, <, Ljava/lang/Void;, Ljava/lang/Void;, TD;>;, Ljava/lang/Runnable;]
superName : Landroid/support/v4/content/ModernAsyncTask;
interfaces : [Ljava/lang/Runnable;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/content/AsyncTaskLoader;
signature : [<D:, Ljava/lang/Object;, >, Landroid/support/v4/content/Loader, <TD;>;]
superName : Landroid/support/v4/content/Loader;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/content/FileProvider$SimplePathStrategy;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/content/FileProvider$PathStrategy;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/content/IntentCompat$IntentCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/content/IntentCompat$IntentCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/content/ModernAsyncTask$2;
signature : [Landroid/support/v4/content/ModernAsyncTask$WorkerRunnable, <TParams;TResult;>;]
superName : Landroid/support/v4/content/ModernAsyncTask$WorkerRunnable;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/graphics/drawable/DrawableCompat$BaseDrawableImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/graphics/drawable/DrawableCompat$DrawableImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/hardware/display/DisplayManagerCompat$JellybeanMr1Impl;
signature : null
superName : Landroid/support/v4/hardware/display/DisplayManagerCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/hardware/display/DisplayManagerCompat$LegacyImpl;
signature : null
superName : Landroid/support/v4/hardware/display/DisplayManagerCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1537
name : Landroid/support/v4/internal/view/SupportSubMenu;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/internal/view/SupportMenu;, Landroid/view/SubMenu;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/media/TransportMediator$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/media/TransportMediatorCallback;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/media/TransportMediator;
signature : null
superName : Landroid/support/v4/media/TransportController;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/ConnectivityManagerCompat$BaseConnectivityManagerCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/ConnectivityManagerCompat$ConnectivityManagerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/ConnectivityManagerCompat$GingerbreadConnectivityManagerCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/ConnectivityManagerCompat$ConnectivityManagerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/ConnectivityManagerCompat$HoneycombMR2ConnectivityManagerCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/ConnectivityManagerCompat$ConnectivityManagerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/ConnectivityManagerCompat$JellyBeanConnectivityManagerCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/ConnectivityManagerCompat$ConnectivityManagerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/TrafficStatsCompat$BaseTrafficStatsCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/TrafficStatsCompat$TrafficStatsCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/net/TrafficStatsCompat$IcsTrafficStatsCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/net/TrafficStatsCompat$TrafficStatsCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/print/PrintHelper$PrintHelperKitkatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/print/PrintHelper$PrintHelperVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/print/PrintHelper$PrintHelperStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/print/PrintHelper$PrintHelperVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/ICUCompat$ICUCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/text/ICUCompat$ICUCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/ICUCompat$ICUCompatImplIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/text/ICUCompat$ICUCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/TextDirectionHeuristicsCompat$AnyStrong;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionAlgorithm;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/TextDirectionHeuristicsCompat$FirstStrong;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionAlgorithm;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1024
name : Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionHeuristicImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/text/TextDirectionHeuristicCompat;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/util/ArrayMap$1;
signature : [Landroid/support/v4/util/MapCollections, <TK;TV;>;]
superName : Landroid/support/v4/util/MapCollections;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/util/ArrayMap;
signature : [<K:, Ljava/lang/Object;, V:, Ljava/lang/Object;, >, Landroid/support/v4/util/SimpleArrayMap, <TK;TV;>;, Ljava/util/Map, <TK;TV;>;]
superName : Landroid/support/v4/util/SimpleArrayMap;
interfaces : [Ljava/util/Map;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/AccessibilityDelegateCompatIcs$AccessibilityDelegateBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/AccessibilityDelegateCompatJellyBean$AccessibilityDelegateBridgeJellyBean;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/GestureDetectorCompat$GestureDetectorCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/GestureDetectorCompat$GestureDetectorCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/GestureDetectorCompat$GestureDetectorCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/GravityCompat$GravityCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/GravityCompat$GravityCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/GravityCompat$GravityCompatImplJellybeanMr1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/GravityCompat$GravityCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/KeyEventCompat$BaseKeyEventVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/KeyEventCompat$KeyEventVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImplJbMr1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MarginLayoutParamsCompat$MarginLayoutParamsCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MenuItemCompat$BaseMenuVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MenuItemCompat$MenuVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MenuItemCompat$HoneycombMenuVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MenuItemCompat$MenuVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MenuItemCompat$IcsMenuVersionImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MenuItemCompatIcs$SupportActionExpandProxy;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MotionEventCompat$BaseMotionEventVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MotionEventCompat$MotionEventVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MotionEventCompat$EclairMotionEventVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/MotionEventCompat$MotionEventVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/PagerTitleStrip$PageListener;
signature : null
superName : Landroid/database/DataSetObserver;
interfaces : [Landroid/support/v4/view/ViewPager$OnPageChangeListener;, Landroid/support/v4/view/ViewPager$OnAdapterChangeListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/PagerTitleStrip$PagerTitleStripImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/PagerTitleStrip$PagerTitleStripImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/PagerTitleStrip$PagerTitleStripImplIcs;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/PagerTitleStrip$PagerTitleStripImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/PagerTitleStrip;
signature : null
superName : Landroid/view/ViewGroup;
interfaces : [Landroid/support/v4/view/ViewPager$Decor;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ScaleGestureDetectorCompat$BaseScaleGestureDetectorImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorCompatKitKatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/VelocityTrackerCompat$BaseVelocityTrackerVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/VelocityTrackerCompat$VelocityTrackerVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/VelocityTrackerCompat$HoneycombVelocityTrackerVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/VelocityTrackerCompat$VelocityTrackerVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewCompat$ViewCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewConfigurationCompat$BaseViewConfigurationVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewConfigurationCompat$ViewConfigurationVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewConfigurationCompat$FroyoViewConfigurationVersionImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewConfigurationCompat$ViewConfigurationVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewPager$MyAccessibilityDelegate;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 16
name : Landroid/support/v4/view/ViewPager$SavedState$1;
signature : [Ljava/lang/Object;, Landroid/support/v4/os/ParcelableCompatCreatorCallbacks, <, Landroid/support/v4/view/ViewPager$SavedState;, >;]
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/os/ParcelableCompatCreatorCallbacks;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/ViewPager$SimpleOnPageChangeListener;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewPager$OnPageChangeListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewParentCompat$ViewParentCompatStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/ViewParentCompat$ViewParentCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityEventCompat$AccessibilityEventStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityEventCompat$AccessibilityEventVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityManagerCompat$AccessibilityManagerIcsImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityManagerCompatIcs$AccessibilityStateChangeListenerBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityManagerCompat$AccessibilityManagerStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityManagerCompat$AccessibilityManagerVersionImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderJellyBeanImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatJellyBean$AccessibilityNodeInfoBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderKitKatImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompatKitKat$AccessibilityNodeInfoBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/CursorAdapter;
signature : null
superName : Landroid/widget/BaseAdapter;
interfaces : [Landroid/widget/Filterable;, Landroid/support/v4/widget/CursorFilter$CursorFilterClient;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/DrawerLayout$AccessibilityDelegate;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/DrawerLayout$SimpleDrawerListener;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/DrawerLayout$DrawerListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/DrawerLayout$ViewDragCallback;
signature : null
superName : Landroid/support/v4/widget/ViewDragHelper$Callback;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/EdgeEffectCompat$BaseEdgeEffectImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectIcsImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/EdgeEffectCompat$EdgeEffectImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ExploreByTouchHelper$ExploreByTouchNodeProvider;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/ExploreByTouchHelper;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ListPopupWindowCompat$BaseListPopupWindowImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/ListPopupWindowCompat$ListPopupWindowImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/ListViewAutoScrollHelper;
signature : null
superName : Landroid/support/v4/widget/AutoScrollHelper;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/PopupMenuCompat$BasePopupMenuImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/PopupMenuCompat$PopupMenuImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplGingerbread;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$1;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnQueryTextListenerCompatBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl$2;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/SearchViewCompatHoneycomb$OnCloseListenerCompatBridge;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$AccessibilityDelegate;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$DragHelperCallback;
signature : null
superName : Landroid/support/v4/widget/ViewDragHelper$Callback;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SlidingPaneLayout$SimplePanelSlideListener;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/SlidingPaneLayout$PanelSlideListener;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImplBase;
signature : null
superName : Ljava/lang/Object;
interfaces : [Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImpl;]
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
signature : null
superName : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/NavUtils$NavUtilsImplJB;
signature : null
superName : Landroid/support/v4/app/NavUtils$NavUtilsImplBase;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ShareCompat$ShareCompatImplICS;
signature : null
superName : Landroid/support/v4/app/ShareCompat$ShareCompatImplBase;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/content/CursorLoader;
signature : [Landroid/support/v4/content/AsyncTaskLoader, <, Landroid/database/Cursor;, >;]
superName : Landroid/support/v4/content/AsyncTaskLoader;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/content/IntentCompat$IntentCompatImplHC;
signature : null
superName : Landroid/support/v4/content/IntentCompat$IntentCompatImplBase;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/graphics/drawable/DrawableCompat$HoneycombDrawableImpl;
signature : null
superName : Landroid/support/v4/graphics/drawable/DrawableCompat$BaseDrawableImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionHeuristicInternal;
signature : null
superName : Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionHeuristicImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionHeuristicLocale;
signature : null
superName : Landroid/support/v4/text/TextDirectionHeuristicsCompat$TextDirectionHeuristicImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/KeyEventCompat$EclairKeyEventVersionImpl;
signature : null
superName : Landroid/support/v4/view/KeyEventCompat$BaseKeyEventVersionImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/MenuItemCompat$IcsMenuVersionImpl;
signature : null
superName : Landroid/support/v4/view/MenuItemCompat$HoneycombMenuVersionImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/view/PagerTabStrip;
signature : null
superName : Landroid/support/v4/view/PagerTitleStrip;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$EclairMr1ViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatHCImpl;
signature : null
superName : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewParentCompat$ViewParentCompatICSImpl;
signature : null
superName : Landroid/support/v4/view/ViewParentCompat$ViewParentCompatStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityEventCompat$AccessibilityEventIcsImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityEventCompat$AccessibilityEventStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityManagerCompat$AccessibilityManagerIcsImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityManagerCompat$AccessibilityManagerStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoIcsImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderJellyBeanImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderKitKatImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat$AccessibilityNodeProviderStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordIcsImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ListPopupWindowCompat$KitKatListPopupWindowImpl;
signature : null
superName : Landroid/support/v4/widget/ListPopupWindowCompat$BaseListPopupWindowImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/PopupMenuCompat$KitKatPopupMenuImpl;
signature : null
superName : Landroid/support/v4/widget/PopupMenuCompat$BasePopupMenuImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1025
name : Landroid/support/v4/widget/ResourceCursorAdapter;
signature : null
superName : Landroid/support/v4/widget/CursorAdapter;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplIcs;
signature : null
superName : Landroid/support/v4/widget/ScrollerCompat$ScrollerCompatImplGingerbread;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;
signature : null
superName : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatStubImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImplJB;
signature : null
superName : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImplBase;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImplJBMR1;
signature : null
superName : Landroid/support/v4/widget/SlidingPaneLayout$SlidingPanelLayoutImplBase;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
signature : null
superName : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/app/ShareCompat$ShareCompatImplJB;
signature : null
superName : Landroid/support/v4/app/ShareCompat$ShareCompatImplICS;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/content/IntentCompat$IntentCompatImplIcsMr1;
signature : null
superName : Landroid/support/v4/content/IntentCompat$IntentCompatImplHC;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/graphics/drawable/DrawableCompat$KitKatDrawableImpl;
signature : null
superName : Landroid/support/v4/graphics/drawable/DrawableCompat$HoneycombDrawableImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl;
signature : null
superName : Landroid/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/KeyEventCompat$HoneycombKeyEventVersionImpl;
signature : null
superName : Landroid/support/v4/view/KeyEventCompat$EclairKeyEventVersionImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$GBViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$EclairMr1ViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatIcsImpl;
signature : null
superName : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatHCImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoJellybeanImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoIcsImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordIcsMr1Impl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordIcsImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatIcsImpl;
signature : null
superName : Landroid/support/v4/widget/SearchViewCompat$SearchViewCompatHoneycombImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 1
name : Landroid/support/v4/widget/SimpleCursorAdapter;
signature : null
superName : Landroid/support/v4/widget/ResourceCursorAdapter;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$HCViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$GBViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatJellybeanMR2Impl;
signature : null
superName : Landroid/support/v4/view/ViewGroupCompat$ViewGroupCompatIcsImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoJellybeanMr2Impl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoJellybeanImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordJellyBeanImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityRecordCompat$AccessibilityRecordIcsMr1Impl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$ICSViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$HCViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoKitKatImpl;
signature : null
superName : Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat$AccessibilityNodeInfoJellybeanMr2Impl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$JBViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$ICSViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$JbMr1ViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$JBViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
---------ApplicationAdapterAnnotateCalls visitClass Start-------
access : 0
name : Landroid/support/v4/view/ViewCompat$KitKatViewCompatImpl;
signature : null
superName : Landroid/support/v4/view/ViewCompat$JbMr1ViewCompatImpl;
interfaces : null
---------ApplicationAdapterAnnotateCalls VisitClass End-------
ApplicationAdapterAnnotateCalls visitEnd called...


*/